# Generated by Django 4.2.7 on 2023-12-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_bankrupt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.IntegerField(max_length=6)),
                ('amount', models.IntegerField(max_length=6)),
            ],
        ),
    ]
